### PR TITLE
Drop IE10 support

### PR DESCRIPTION
**Pull request by GoodForOneFare**
This doesn't change the polyfills output by `import 'babel-polyfill';`, so it's really just a statement of intent ¯\\_(ツ)_/¯

## Supported browser changes
* [Before](http://browserl.ist/?q=last+3+chrome+versions%2C+last+3+firefox+versions%2C+last+2+versions%2C+safari+%3E%3D+8%2C+ios+%3E%3D+8%2C+ie+%3E%3D+11%2C+explorermobile+%3E%3D+11%2C+android+%3E%3D+4.4) - 90.54% global usage
* [After](http://browserl.ist/?q=last+3+chrome+versions%2C+last+3+firefox+versions%2C+safari+%3E%3D+8%2C+ios+%3E%3D+8%2C+ie+%3E%3D+11%2C+explorermobile+%3E%3D+11%2C+android+%3E%3D+4.4%2C+OperaMini+all%2C+last+1+UCAndroid+version%2C+last+3+FirefoxAndroid+versions%2C+last+3+ChromeAndroid+versions%2C+last+1+samsung+version%2C+last+2+opera+versions%2C+last+2+edge+versions) - 90% global usage

### Dropped mobile browsers
| Browser | Version | Global usage |
| ----- | ----- | ----- |
| QQ Browser | 1.2 | 0% |
| Baidu Browser | 7.12 | 0% |
| Blackberry Browser | 10 | 0.07% |
| Blackberry Browser | 7 | 0.02% |
| IE Mobile | 10 | 0.03% |
| Opera Mobile | 37 | 0.01% |
| Opera Mobile | 12.1 | 0% |
| Samsung Internet | 5 | 0.35% |

### Dropped desktop browsers
| Browser | Version | Global usage |
| ----- | ----- | ----- |
| IE | 10 | 0.13% |

### CODE REVIEW

**Comment by lemonmade** [comment]
Do we know if anyone using this config is still supporting IE10? I am thinking mostly of marketing projects but unsure if they actually use Babel or not.

**Comment by leo-shopify** [comment]
Brochure2 in particular includes its own version of [browserlist](https://github.com/Shopify/brochure2/blob/8effbcc880756ac7b951723a94bf1885b946f327/browserslist#L1-L9).
It looks like they are migrating to use [sewing-kit, babel and es6](https://github.com/Shopify/brochure2/commit/39011bd5791d679ab83bedaa9a7f334d5cb7e554)

**Comment by mattdrose** [comment]
👋 brochure and marketing assets manage their own browserlists. We added [our own preset](https://github.com/Shopify/marketing_assets/blob/master/config/marketing-assets-preset.js) as soon as we heard babel-preset-shopify would be dropping IE11.

**Comment by lemonmade** [comment]
@mattdrose I'd like whatever you have to be considered in this tool as well, ideally there is some sort of enum for the type of project you are building and we pick the right browsers for that project.

**Comment by mattdrose** [comment]
@lemonmade if there was a marketing preset, that would be 💯

**Comment by mattdrose** [comment]
Opened issue here https://github.com/Shopify/babel-preset-shopify/issues/23

As long as you bump version with a changelog, I wouldn't say it's a blocker to this PR.

**Comment by brendo** [comment]
🔔Now that time has passed the proposed before/after values have changed slightly:

Before: Global coverage 88.12%
After: Global coverage 87.63%

**Pull request closed without merging**
