### PR TITLE
Bump babel-preset-shopify outdated dependencies

### LINKED ISSUE #30: Update outdated depedencies

### PR DESCRIPTION
**Pull request by ismail-syed**
Closes #30

### CODE REVIEW

**Comment by brendo** [comment]
@ismail-syed can I help push this forward? We'd love this to get the updated `browserslist` capabilities in particular.

**Comment by ismail-syed** [comment]
@brendo yes, ofc. Feel free to take this over if you'd like.

**Comment by brendo** [comment]
Have updated this PR to bump things to the latest* version and backfilled the CHANGELOG.

I think this should ship as 16.6.0.

*I think a follow-up PR should migrate dependencies to use the `@babel` namespace as some dependencies (`@babel-preset-env`) are no longer receiving updates and development has continued in it's new home. This migration may be a little messier so I felt it was best to ship this as a low risk change for consumers now and do the above work and release as a v17.

**Review by lemonmade — APPROVED** [review]
@brendo's plan sounds good to me. Can we make sure we have an issue to update to the latest `@babel`-namespaced packages/ Babel 7?

**Comment by brendo** [comment]
Raised #31 :)

**Pull request merged**
